// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj4o6PzXMsqy1cb5TvUIgoNSs0fy7t96k',
    appId: '1:425885043162:web:ff689a332c8b37268798e3',
    messagingSenderId: '425885043162',
    projectId: 'electivagrupo2-58545',
    authDomain: 'electivagrupo2-58545.firebaseapp.com',
    storageBucket: 'electivagrupo2-58545.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmg00ise3KlG3j4B93nVe2_8vXHu8uIFA',
    appId: '1:425885043162:android:327320ec20d153618798e3',
    messagingSenderId: '425885043162',
    projectId: 'electivagrupo2-58545',
    storageBucket: 'electivagrupo2-58545.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx1kfNvWUBJipvhai2Mk9aN1TL3xU1BIc',
    appId: '1:425885043162:ios:2869425d703a8d4c8798e3',
    messagingSenderId: '425885043162',
    projectId: 'electivagrupo2-58545',
    storageBucket: 'electivagrupo2-58545.firebasestorage.app',
    iosBundleId: 'com.example.parqueadero2025G2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDx1kfNvWUBJipvhai2Mk9aN1TL3xU1BIc',
    appId: '1:425885043162:ios:2869425d703a8d4c8798e3',
    messagingSenderId: '425885043162',
    projectId: 'electivagrupo2-58545',
    storageBucket: 'electivagrupo2-58545.firebasestorage.app',
    iosBundleId: 'com.example.parqueadero2025G2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAj4o6PzXMsqy1cb5TvUIgoNSs0fy7t96k',
    appId: '1:425885043162:web:fe07246652b8cad28798e3',
    messagingSenderId: '425885043162',
    projectId: 'electivagrupo2-58545',
    authDomain: 'electivagrupo2-58545.firebaseapp.com',
    storageBucket: 'electivagrupo2-58545.firebasestorage.app',
  );
}
